name: Opengrep

on:
  pull_request: {}
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  opengrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Install Opengrep
        run: curl -fsSL https://raw.githubusercontent.com/opengrep/opengrep/main/install.sh | bash
        
      - name: Run Opengrep
        # This uses the correct path from your logs!
        run: $HOME/.opengrep/cli/latest/opengrep scan --config auto
