name: Opengrep Local Rules Scan

on:
  pull_request: {}
  push:
    branches: [main]
  # Allows you to run this scan manually from the GitHub UI
  workflow_dispatch: {} 

jobs:
  opengrep:
    name: Run Opengrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Opengrep
        run: curl -fsSL https://raw.githubusercontent.com/opengrep/opengrep/main/install.sh | bash

      - name: Run Opengrep Scan
        # Using the absolute path for safety, and pointing to your local rules folder
        run: $HOME/.local/bin/opengrep scan --config .opengrep-rules/
